'use strict';
/**
 * 英文词典：键 = 页面/接口中出现的中文短语，值 = 英文。
 * 未收录的短语会原样显示（例如人名、公司名，故意不译）。
 * 注意：键必须与原文完全一致（含繁简差异），改动请同时检查页面效果。
 */
module.exports = {
  /* ===== 通用界面 ===== */
  '请选择': 'Please select', '請選擇': 'Please select', '请选择部门': 'Please select department',
  '请选择日期': 'Please select date', '请选择班別': 'Please select shift',
  '请选择线别': 'Please select line', '请选择站别': 'Please select station',
  '请选择类别': 'Please select category', '请选择部门线别': 'Please select department/line',
  '请选择部门日期': 'Please select department/date',
  '请输入': 'Please enter', '请输入内容': 'Please enter content', '请输入內容': 'Please enter content',
  '请输入编号': 'Please enter No.', '请输入数量': 'Please enter quantity',
  '请输入數量': 'Please enter quantity', '请输入日期': 'Please enter date',
  '请输入备注信息': 'Please enter remark', '请输入姓名': 'Please enter name',
  '请输入用户名': 'Please enter username', '请输入条码': 'Please enter barcode',
  '请输入查询内容': 'Please enter search content', '请輸入查詢內容': 'Please enter search content',
  '请输入工號': 'Please enter employee ID', '请输入维修时间': 'Please enter repair time',
  '请输入积压数量': 'Please enter backlog quantity',
  '请输入物品類別': 'Please enter item category', '请输入物品型號': 'Please enter item model',
  '请输入數據説明信息': 'Please enter data description',
  '请输版本': 'Please enter version', '请输程式名': 'Please enter program name',
  '请输機種名': 'Please enter model name',
  '保存': 'Save', '保存成功': 'Saved successfully', '提交更改': 'Submit changes',
  '重置': 'Reset', '取消': 'Cancel', '确认': 'Confirm', '確認': 'Confirm',
  '删除': 'Delete', '刪除': 'Delete', '修改': 'Edit', '编辑': 'Edit', '新增行': 'Add row',
  '编辑行': 'Edit row', '查询': 'Query', '查询记录': 'Query records', '查询内容': 'Search content',
  '查詢內容': 'Search content', '查找': 'Search', '搜索': 'Search', '搜索记录': 'Search records',
  '返回': 'Return', '刷新': 'Refresh', '刷新状态': 'Refresh status', '导出': 'Export',
  '导出数据': 'Export data', '导出表格': 'Export table', '导入': 'Import', '清空': 'Clear',
  '清空数据': 'Clear data', '清空条件': 'Clear filter', '执行': 'Execute', '执行完成': 'Done',
  '输入': 'Input', '输出': 'Output', '操作': 'Action', '状态': 'Status', '合计': 'Total',
  '总数': 'Total', '总行数': 'Total rows', '总分': 'Total score', '正确率': 'Accuracy',
  '百分比': 'Percentage', '平均': 'Average', '立即提交': 'Submit now', '提交答案': 'Submit answer',
  '生产管理系统': 'Production Management System', '内部窗口': 'Internal window',
  '加载中': 'Loading', '在新标签页打开': 'Open in new tab', '回到公告': 'Back to notice board',
  '折叠 / 展开侧边栏': 'Collapse / expand sidebar', '已保存': 'Saved',

  /* ===== 登录与用户 ===== */
  '登': 'Login', '登陆': 'Login', '用戶登录': 'User login', '用户登录': 'User login',
  '登录成功': 'Login successful', '登录中': 'Signing in',
  '密码': 'Password', '密码错误': 'Wrong password', '密码不能为空': 'Password cannot be empty',
  '显示密码': 'Show password', '隐藏密码': 'Hide password',
  '用户名或密码错误': 'Wrong username or password', '验证码错误': 'Wrong captcha',
  '网络异常，请稍后重试': 'Network error, please try again later',
  '记住密码': 'Remember password', '用户名': 'Username', '用户名或者邮箱': 'Username or email',
  '用户名不能为空': 'Username cannot be empty', '用户': 'User', '人员': 'Personnel',
  '验证码': 'Captcha', '图形验证码': 'Image captcha', '验证码不能为空': 'Captcha cannot be empty',
  '看不清？点击图片换一张': 'Unclear? Click the image for another one',
  '大写锁定已开启': 'Caps Lock is on',
  '验证通过': 'Verified', '退出': 'Logout', '基本资料': 'Profile', '安全设置': 'Security settings',
  '输入工号，并确认': 'Enter employee ID and confirm', '填写自己姓名': 'Enter your name',
  '数据': 'Data', '数据表': 'Tables', '数据库导出': 'Database export',
  '工號': 'Employee ID', '數據庫沒有這個工號': 'No such employee ID in database',

  /* ===== 顶部导航与模块名 ===== */
  '常用': 'Common', '其它': 'Others', '其它系统': 'Other systems', '其它事項': 'Others',
  '公告': 'Notice', '文件': 'File', '设备维护': 'Equipment maintenance',
  '备品管理': 'Spare parts management', '備品管理': 'Spare parts management',
  '备品管理系统': 'Spare parts management system', '管理系统': 'Management system',
  '良率改善': 'Yield improvement', '良率查詢': 'Yield query', '停机率': 'Downtime rate',
  '良率': 'Yield', '测试题库添加': 'Add test question', '测验': 'Test', '測驗': 'Test',
  '知识测验': 'Knowledge test', '知識測驗': 'Knowledge test', '知識测验': 'Knowledge test',
  '測試分數': 'Test score', '测试分数': 'Test score', '分數': 'Score',
  '高级教程': 'Advanced tutorial', '教育训练': 'Training', '點檢表': 'Inspection sheet',
  '日常點檢表': 'Routine inspection sheet', '每日开线點檢表': 'Daily line-start inspection sheet',
  '治具點檢表': 'Fixture inspection sheet', '治具點檢記錄': 'Fixture inspection record',
  '測試程式修改記錄': 'Test program change record',
  '測試程式修改記錄表': 'Test program change record',
  '測試資料查詢': 'Test data search', '资料查找': 'Data search', '交接': 'Handover',
  '交接记录': 'Handover record', '交接記錄': 'Handover record',
  '数据库管理': 'Database management', '数据库管理页仅允许本机访问': 'Database management is only accessible from this machine',
  '局域网不允许访问数据库管理页': 'LAN access to database management is not allowed',
  '数据库管理需要密码': 'A password is required to manage the database',
  '数据库管理页面缺失': 'Database management page is missing',
  '需要密码才能管理数据库': 'A password is required to manage the database',
  '请先输入管理密码': 'Please enter the admin password first',

  /* ===== 表头与字段 ===== */
  '日期': 'Date', '时间': 'Time', '時間': 'Time', '开始日期': 'Start date', '结束日期': 'End date',
  '日期起': 'From', '止': 'To', '班別': 'Shift', '白班': 'Day shift', '夜班': 'Night shift',
  '部门': 'Department', '部門': 'Department', '线别': 'Line', '綫體': 'Line', '站别': 'Station',
  '机种': 'Model', '機種': 'Model', '型号': 'Model', '型號': 'Model', '机台型号': 'Machine model',
  '機臺': 'Machine', '机台编号': 'Machine No.', '设备编号': 'Equipment No.',
  '设备功率参数': 'Equipment power parameter', '数量': 'Quantity', '數量': 'Quantity',
  '库存': 'Stock', '庫存': 'Stock', '安全庫存': 'Safety stock', '庫存説明': 'Stock description',
  '编号': 'No.', '編號': 'No.', '物品': 'Item', '物品类别': 'Item category',
  '物品類別': 'Item category', '种类': 'Category', '厂商': 'Vendor', '软件': 'Software',
  '硬件': 'Hardware', '上位机': 'Host PC', '轨道': 'Track', '治具': 'Fixture',
  '治具結構': 'Fixture structure', '探針': 'Probe', '探針使用次數': 'Probe usage count',
  '备注信息': 'Remark', '説明': 'Description', '良品': 'Good', '不良': 'Defect',
  '不良零件數': 'Defective parts', '有板': 'Board present', '有板信號': 'Board-present signal',
  '目视': 'Visual', '目视主机': 'Visual host', '测试桌': 'Test bench', '积压': 'Backlog',
  '记录': 'Record', '記錄': 'Record', '修改者': 'Modified by', '確認者': 'Approver',
  '檢查者': 'Inspector', '维修人员': 'Repairer', '维修时间': 'Repair time',
  '修改内容': 'Change content', '修改原因': 'Change reason', '修改記錄': 'Change record',
  '原程式名': 'Old program name', '舊程式名': 'Old program name',
  '新程式名': 'New program name', '修改后程式名': 'New program name',
  '故障描述': 'Fault description', '故障处理分析': 'Fault analysis', '故障类别': 'Fault category',
  '故障原因': 'Fault cause', '故障记录': 'Fault record', '故障搜索': 'Fault search',
  '停机时间': 'Downtime', '次数': 'Count', '次': 'time(s)', '天': 'day(s)', '日': 'Day',
  '月': 'Month', '张': 'tables', '行': 'row(s)', '张表': 'tables', '条记录': 'records',
  '表': 'Tables', '脚本': 'Script', '获取的数据': 'fetched data', '幾臺': 'Quantity',
  '是否確定刪除': 'Are you sure you want to delete',
  '共': 'Total', '大小': 'Size', '主键': 'PK', '狀態': 'Status', '问题': 'Question',
  '問題': 'Question', '答案': 'Answer', '題目類型': 'Question type', '題庫': 'Question bank',
  '添加題目': 'Add question', '新建物品': 'New item', '新建記錄': 'New record',
  '新建交接記錄': 'New handover record', '创建记录': 'Create record',
  '刪除物品': 'Delete item', '刪除交接記錄': 'Delete handover record',
  '編號查询': 'Search by No.', '備品出庫': 'Spare parts outbound', '備份': 'Backup',
  '機臺備品': 'Machine spare parts', '治具備品': 'Fixture spare parts',
  '出庫': 'Out', '入庫': 'In', '入': 'In',

  /* ===== 图表与统计 ===== */
  '图表': 'Chart', '数据图表': 'Data chart', '记录图表': 'Records chart',
  '各线良率': 'Yield by line', '平均良率': 'Average yield', '每日平均良率': 'Daily average yield',
  '一周每日平均良率': 'Weekly daily average yield', '良率產出': 'Yield output',
  '本年停机率': 'Downtime rate this year', '本月停机率': 'Downtime rate this month',
  '本周停机率': 'Downtime rate this week', '平均停机率': 'Average downtime rate',
  '各线停机率': 'Downtime rate by line', '各线停机时间': 'Downtime by line',
  '各线停线时间': 'Line stop time by line', '各线停线次数': 'Line stop count by line',
  '各种机台停机时间': 'Downtime by machine type',
  '近五日停机时间分布': 'Downtime in the last 5 days',
  '年统计': 'Yearly', '月趋势': 'Monthly trend', '周趋势': 'Weekly trend',
  '周趋势 (近7天)': 'Weekly trend (last 7 days)',
  '月趋势 (近30天)': 'Monthly trend (last 30 days)',
  '年统计 (近12月)': 'Yearly (last 12 months)',
  '初始化停机率图表': 'Initialize downtime chart', '近': 'Last',
  '設備統計表': 'Equipment statistics', '載板清潔': 'Carrier cleaning',
  '治具載板清潔': 'Fixture carrier cleaning', '點檢項': 'Inspection item',

  /* ===== 数据库管理页 ===== */
  '数据库文件': 'Database file', '数据表': 'Tables', '导出数据库文件': 'Export database file',
  '导入数据库': 'Import database', '替换整个数据库': 'Replace the whole database',
  '选择文件': 'Select file', '开始导入': 'Start import', '确认口令': 'Confirmation code',
  '整个数据库文件替换（原数据全部丢弃': 'Replace the whole database file (ALL current data will be lost',
  '脚本导入（脚本里已有的表会被覆盖，其它表保留': 'SQL script import (tables in the script will be overwritten, others kept',
  '勾选要清空的表（会同时重置自增序号，操作不可撤销':
    'Check the tables to clear (auto-increment will also be reset, cannot be undone',
  '此页面可直接读写数据库，请谨慎操作': 'This page reads and writes the database directly, please be careful',
  '该物品暂未填写说明': 'No description has been entered for this item',
  '点击查看说明': 'Click to view the description',
  '说明加载失败，请重试': 'Failed to load the description, please retry',
  '清空、导入、执行 SQL 均需在弹窗中输入 CONFIRM 二次确认；操作前建议先导出数据库文件做备份。':
    'To clear, import or execute SQL you must type CONFIRM in the dialog; exporting a backup first is recommended.',
  '二次确认，操作前建议先「导出数据库文件」做备份':
    'requires double confirmation; exporting a backup first is recommended',
  '均需在弹窗中输入': 'must all be typed in the dialog', '全部表': 'All tables',
  '导出时间': 'Export time', '导出本表': 'Export this table', '表数据': 'Table data',
  '执行器': 'Executor', '执行确认': 'Confirm execution', '确定清空': 'Confirm clear',
  '确定删除': 'Confirm delete', '删除确认': 'Delete confirmation',
  '确定执行下面的': 'Are you sure you want to execute the following',
  '语句会返回结果；其它语句': 'statements return results; other statements',
  '会直接执行': 'will be executed directly', '以确认执行': 'to confirm execution',
  '以确认导入操作': 'to confirm the import', '以确认清空操作': 'to confirm clearing',
  '关键字（全部字段模糊匹配': 'Keyword (fuzzy match on all fields',
  '点击行尾的「编辑': 'Click "Edit', '删除」操作': 'Delete" at the end of the row',
  '(点击行尾的编辑 / 删除按钮操作)': '(click Edit / Delete at the end of the row)',
  '行（最多显示': 'rows (max', '已保存（影响': 'Saved (affected ',
  '已删除（影响': 'Deleted (affected ', '共': 'Total',

  /* ===== 提示与错误 ===== */
  '失败': 'failed', '启动失败': 'Startup failed', '导入失败': 'Import failed',
  '加载失败': 'Load failed', '数据获取失败': 'Failed to fetch data',
  '网络响应异常': 'Network error', '服务返回异常': 'Server returned an error',
  '请求失败': 'Request failed', '文件': 'File', '文件内容': 'file content',
  '文件中没有任何数据表': 'The file contains no data table',
  '没有收到文件内容': 'No file content received', '无法识别的': 'Unrecognized',
  '没有可写入的字段': 'No field to insert', '没有需要更新的字段': 'No field to update',
  '没有数据': 'No data', '缺少': 'Missing', '缺少主键列': 'missing primary key column',
  '无法自动补齐': 'cannot be added automatically', '补列': 'added column',
  '已自动补列': 'auto-added column', '数据库尚未初始化': 'Database not initialized',
  '表不存在': 'Table not found', '列不存在': 'Column not found', '未知操作': 'Unknown action',
  '不支持的导出格式': 'Unsupported export format', '请先选择文件': 'Please select a file first',
  '请先选择一张表': 'Please select a table first',
  '请至少选择一张表': 'Please select at least one table',
  '数据库导出': 'Database export', '数据库文件': 'Database file',
  '数据库中已存在数据': 'Data already exists in the database',
  '跳过': 'Skip', '的导入': ' import', '若要用': 'To use', '重建，请删除': 'to rebuild, please delete',
  '已导入': 'Imported', '已清空': 'Cleared', '已用': 'Used',
  '没有数据，请调整查询条件后重试': 'No data, please adjust the search condition and retry',
  '暂无数据，请调整查询条件后重试': 'No data, please adjust the search condition and retry',
  '的记录': ' record',
  '时间区间选择错误': 'Invalid time range', '时间格式错误': 'Invalid time format',
  '日期選擇錯誤': 'Invalid date selection', '日期输入不正确': 'Invalid date input',
  '时间必须是数字': 'Time must be a number', '时间必须必须是数字': 'Time must be a number',
  '数量必须是数字': 'Quantity must be a number', '数量必须必须是数字': 'Quantity must be a number',
  '數量必须是数字': 'Quantity must be a number', '數量必须是数字，單位盒': 'Quantity must be a number, unit box',
  '积压必须是数字': 'Backlog must be a number', '未选择日期范围': 'No date range selected',
  '未检测到可用的局域网网卡地址': 'No usable LAN address detected',
  '本机访问': 'Local access', '局域网访问（其它电脑用下面的地址打开': 'LAN access (open this address on other computers',
  '端口': 'Port', '已被占用，本次改用': 'is already in use, switched to',
  '及其备选端口均被占用。请关闭占用': 'and its fallback ports are all in use. Please close the program using',
  '端口的程序': 'port program', '另一个': 'another', '连同': 'together with',
  '实例）后重试': 'instance) and retry', '后重新启动': ' then restart',
  '请释放该端口后重启本程序': 'please free the port and restart this program',
  '如需恢复': 'To restore', '首次运行：正在导入': 'First run: importing',
  '未配置远程密码（环境变量': 'Remote password not configured (env var',

  /* ===== 知识点检（测验相关） ===== */
  '環境溫濕度不達標': 'Temperature/humidity out of spec',
  '日常點檢不到位': 'Routine inspection not performed',
  '設備未按時保養': 'Equipment not maintained on schedule',
  '未按流程作業': 'Not following the procedure',
  '無用資料沒有及時清理': 'Unused data not cleaned up in time',
  '無系統': 'None', '开始答题': 'Start quiz', '開始答題': 'Start quiz',
  '正確選項': 'Correct option', '优秀！全部正确': 'Excellent! All correct',
  '不错，继续努力': 'Good, keep it up', '需要加强练习哦': 'Keep practicing',
  '非必填': 'Optional', '请选择日期班別': 'Please select date/shift',
};
