'use strict';
/**
 * 越南文词典：键 = 页面/接口中出现的中文短语，值 = 越南文。
 * 未收录的短语会原样显示（例如人名、公司名，故意不译）。
 * 注意：键必须与原文完全一致（含繁简差异），改动请同时检查页面效果。
 */
module.exports = {
  /* ===== 通用界面 ===== */
  '请选择': 'Vui lòng chọn', '請選擇': 'Vui lòng chọn', '请选择部门': 'Vui lòng chọn bộ phận',
  '请选择日期': 'Vui lòng chọn ngày', '请选择班別': 'Vui lòng chọn ca',
  '请选择线别': 'Vui lòng chọn chuyền', '请选择站别': 'Vui lòng chọn trạm',
  '请选择类别': 'Vui lòng chọn loại', '请选择部门线别': 'Vui lòng chọn bộ phận/chuyền',
  '请选择部门日期': 'Vui lòng chọn bộ phận/ngày', '请选择日期班別': 'Vui lòng chọn ngày/ca',
  '请输入': 'Vui lòng nhập', '请输入内容': 'Vui lòng nhập nội dung', '请输入內容': 'Vui lòng nhập nội dung',
  '请输入编号': 'Vui lòng nhập số', '请输入数量': 'Vui lòng nhập số lượng',
  '请输入數量': 'Vui lòng nhập số lượng', '请输入日期': 'Vui lòng nhập ngày',
  '请输入备注信息': 'Vui lòng nhập ghi chú', '请输入姓名': 'Vui lòng nhập họ tên',
  '请输入用户名': 'Vui lòng nhập tên đăng nhập', '请输入条码': 'Vui lòng nhập mã vạch',
  '请输入查询内容': 'Vui lòng nhập nội dung tìm kiếm',
  '请輸入查詢內容': 'Vui lòng nhập nội dung tìm kiếm',
  '请输入工號': 'Vui lòng nhập mã nhân viên',
  '请输入维修时间': 'Vui lòng nhập thời gian sửa chữa',
  '请输入积压数量': 'Vui lòng nhập số tồn đọng',
  '请输入物品類別': 'Vui lòng nhập loại vật tư',
  '请输入物品型號': 'Vui lòng nhập model vật tư',
  '请输入數據説明信息': 'Vui lòng nhập mô tả dữ liệu',
  '请输版本': 'Vui lòng nhập phiên bản', '请输程式名': 'Vui lòng nhập tên chương trình',
  '请输機種名': 'Vui lòng nhập tên model',
  '保存': 'Lưu', '保存成功': 'Lưu thành công', '提交更改': 'Gửi thay đổi',
  '重置': 'Đặt lại', '取消': 'Hủy', '确认': 'Xác nhận', '確認': 'Xác nhận',
  '删除': 'Xóa', '刪除': 'Xóa', '修改': 'Sửa', '编辑': 'Sửa', '新增行': 'Thêm dòng',
  '编辑行': 'Sửa dòng', '查询': 'Truy vấn', '查询记录': 'Truy vấn bản ghi',
  '查询内容': 'Nội dung tìm', '查詢內容': 'Nội dung tìm', '查找': 'Tìm', '搜索': 'Tìm kiếm',
  '搜索记录': 'Tìm bản ghi', '返回': 'Trả về', '刷新': 'Làm mới', '刷新状态': 'Làm mới trạng thái',
  '导出': 'Xuất', '导出数据': 'Xuất dữ liệu', '导出表格': 'Xuất bảng', '导入': 'Nhập dữ liệu',
  '清空': 'Xóa hết', '清空数据': 'Xóa dữ liệu', '清空条件': 'Xóa điều kiện',
  '执行': 'Thực hiện', '执行完成': 'Thực hiện xong', '输入': 'Nhập', '输出': 'Xuất',
  '操作': 'Thao tác', '状态': 'Trạng thái', '狀態': 'Trạng thái', '合计': 'Tổng cộng',
  '总数': 'Tổng', '总行数': 'Tổng số dòng', '总分': 'Tổng điểm', '正确率': 'Độ chính xác',
  '百分比': 'Phần trăm', '平均': 'Trung bình', '立即提交': 'Gửi ngay', '提交答案': 'Gửi đáp án',

  /* ===== 登录与用户 ===== */
  '登': 'Đăng nhập', '登陆': 'Đăng nhập', '用戶登录': 'Đăng nhập người dùng',
  '登录成功': 'Đăng nhập thành công', '密码': 'Mật khẩu', '密码错误': 'Sai mật khẩu',
  '密码不能为空': 'Mật khẩu không được để trống', '记住密码': 'Nhớ mật khẩu',
  '用户名': 'Tên đăng nhập', '用户名或者邮箱': 'Tên đăng nhập hoặc email',
  '用户名不能为空': 'Tên đăng nhập không được để trống', '用户': 'Người dùng',
  '人员': 'Nhân viên', '验证码': 'Mã xác thực', '图形验证码': 'Mã xác thực hình ảnh',
  '验证码不能为空': 'Mã xác thực không được để trống', '验证通过': 'Xác thực thành công',
  '退出': 'Đăng xuất', '基本资料': 'Thông tin cơ bản', '安全设置': 'Cài đặt bảo mật',
  '输入工号，并确认': 'Nhập mã nhân viên và xác nhận', '填写自己姓名': 'Điền họ tên của bạn',
  '数据': 'Dữ liệu', '数据表': 'Bảng dữ liệu', '数据库导出': 'Xuất cơ sở dữ liệu',
  '工號': 'Mã nhân viên', '數據庫沒有這個工號': 'CSDL không có mã nhân viên này',

  /* ===== 顶部导航与模块名 ===== */
  '常用': 'Thường dùng', '其它': 'Khác', '其它系统': 'Hệ thống khác', '其它事項': 'Khác',
  '公告': 'Thông báo', '文件': 'Tệp', '设备维护': 'Bảo trì thiết bị',
  '备品管理': 'Quản lý linh kiện', '備品管理': 'Quản lý linh kiện',
  '备品管理系统': 'Hệ thống quản lý linh kiện', '管理系统': 'Hệ thống quản lý',
  '良率改善': 'Cải thiện tỷ lệ đạt', '良率查詢': 'Truy vấn tỷ lệ đạt',
  '停机率': 'Tỷ lệ dừng máy', '良率': 'Tỷ lệ đạt', '测试题库添加': 'Thêm câu hỏi test',
  '测验': 'Kiểm tra', '測驗': 'Kiểm tra', '知识测验': 'Kiểm tra kiến thức',
  '知識測驗': 'Kiểm tra kiến thức', '知識测验': 'Kiểm tra kiến thức',
  '測試分數': 'Điểm kiểm tra', '测试分数': 'Điểm kiểm tra', '分數': 'Điểm',
  '高级教程': 'Hướng dẫn nâng cao', '教育训练': 'Đào tạo', '點檢表': 'Phiếu kiểm tra',
  '日常點檢表': 'Phiếu kiểm tra hàng ngày', '每日开线點檢表': 'Phiếu kiểm tra đầu ngày',
  '治具點檢表': 'Phiếu kiểm tra jig', '治具點檢記錄': 'Bản ghi kiểm tra jig',
  '測試程式修改記錄': 'Bản ghi sửa chương trình test',
  '測試程式修改記錄表': 'Bảng ghi sửa chương trình test',
  '測試資料查詢': 'Truy vấn dữ liệu test', '资料查找': 'Tìm dữ liệu', '交接': 'Bàn giao',
  '交接记录': 'Bản ghi bàn giao', '交接記錄': 'Bản ghi bàn giao',
  '数据库管理': 'Quản lý cơ sở dữ liệu',
  '数据库管理页仅允许本机访问': 'Trang quản lý CSDL chỉ cho phép truy cập từ máy này',
  '局域网不允许访问数据库管理页': 'Không cho phép truy cập trang quản lý CSDL từ mạng LAN',
  '数据库管理需要密码': 'Quản lý CSDL cần mật khẩu',
  '数据库管理页面缺失': 'Thiếu trang quản lý CSDL',
  '需要密码才能管理数据库': 'Cần mật khẩu để quản lý CSDL',
  '请先输入管理密码': 'Vui lòng nhập mật khẩu quản trị trước',

  /* ===== 表头与字段 ===== */
  '日期': 'Ngày', '时间': 'Thời gian', '時間': 'Thời gian', '开始日期': 'Ngày bắt đầu',
  '结束日期': 'Ngày kết thúc', '日期起': 'Từ ngày', '止': 'Đến', '班別': 'Ca',
  '白班': 'Ca ngày', '夜班': 'Ca đêm', '部门': 'Bộ phận', '部門': 'Bộ phận',
  '线别': 'Chuyền', '綫體': 'Chuyền', '站别': 'Trạm', '机种': 'Model', '機種': 'Model',
  '型号': 'Model', '型號': 'Model', '机台型号': 'Model máy', '機臺': 'Máy',
  '机台编号': 'Số máy', '设备编号': 'Số thiết bị', '设备功率参数': 'Thông số công suất thiết bị',
  '数量': 'Số lượng', '數量': 'Số lượng', '库存': 'Tồn kho', '庫存': 'Tồn kho',
  '安全庫存': 'Tồn kho an toàn', '庫存説明': 'Mô tả tồn kho', '编号': 'Số', '編號': 'Số',
  '物品': 'Vật tư', '物品类别': 'Loại vật tư', '物品類別': 'Loại vật tư', '种类': 'Loại',
  '厂商': 'Nhà cung cấp', '软件': 'Phần mềm', '硬件': 'Phần cứng', '上位机': 'Máy chủ',
  '轨道': 'Ray', '治具': 'Jig', '治具結構': 'Kết cấu jig', '探針': 'Đầu dò',
  '探針使用次數': 'Số lần dùng đầu dò', '备注信息': 'Ghi chú', '説明': 'Mô tả',
  '良品': 'Hàng đạt', '不良': 'Lỗi', '不良零件數': 'Số linh kiện lỗi',
  '有板': 'Có bảng mạch', '有板信號': 'Tín hiệu có bảng mạch', '目视': 'Kiểm tra mắt',
  '目视主机': 'Máy kiểm tra mắt', '测试桌': 'Bàn test', '积压': 'Tồn đọng',
  '记录': 'Bản ghi', '記錄': 'Bản ghi', '修改者': 'Người sửa', '確認者': 'Người xác nhận',
  '檢查者': 'Người kiểm tra', '维修人员': 'Người sửa chữa', '维修时间': 'Thời gian sửa chữa',
  '修改内容': 'Nội dung sửa', '修改原因': 'Lý do sửa', '修改記錄': 'Bản ghi sửa',
  '原程式名': 'Tên chương trình cũ', '舊程式名': 'Tên chương trình cũ',
  '新程式名': 'Tên chương trình mới', '修改后程式名': 'Tên chương trình mới',
  '故障描述': 'Mô tả lỗi', '故障处理分析': 'Phân tích xử lý lỗi', '故障类别': 'Loại lỗi',
  '故障原因': 'Nguyên nhân lỗi', '故障记录': 'Bản ghi lỗi', '故障搜索': 'Tìm lỗi',
  '停机时间': 'Thời gian dừng máy', '次数': 'Số lần', '次': 'lần', '天': 'ngày', '日': 'Ngày',
  '月': 'Tháng', '张': 'bảng', '行': 'dòng', '张表': 'bảng', '条记录': 'bản ghi',
  '表': 'Bảng', '脚本': 'Script', '获取的数据': 'dữ liệu nhận được', '幾臺': 'Số lượng',
  '是否確定刪除': 'Bạn có chắc muốn xóa',
  '共': 'Tổng', '大小': 'Kích thước', '主键': 'Khóa chính', '问题': 'Câu hỏi',
  '問題': 'Câu hỏi', '答案': 'Đáp án', '題目類型': 'Loại câu hỏi', '題庫': 'Ngân hàng câu hỏi',
  '添加題目': 'Thêm câu hỏi', '新建物品': 'Tạo vật tư', '新建記錄': 'Tạo bản ghi',
  '新建交接記錄': 'Tạo bản ghi bàn giao', '创建记录': 'Tạo bản ghi',
  '刪除物品': 'Xóa vật tư', '刪除交接記錄': 'Xóa bản ghi bàn giao',
  '編號查询': 'Tìm theo số', '備品出庫': 'Xuất linh kiện', '備份': 'Sao lưu',
  '機臺備品': 'Linh kiện máy', '治具備品': 'Linh kiện jig',
  '出庫': 'Xuất', '入庫': 'Nhập', '入': 'Nhập',

  /* ===== 图表与统计 ===== */
  '图表': 'Biểu đồ', '数据图表': 'Biểu đồ dữ liệu', '记录图表': 'Biểu đồ bản ghi',
  '各线良率': 'Tỷ lệ đạt theo chuyền', '平均良率': 'Tỷ lệ đạt trung bình',
  '每日平均良率': 'Tỷ lệ đạt trung bình ngày',
  '一周每日平均良率': 'Tỷ lệ đạt trung bình tuần', '良率產出': 'Sản lượng đạt',
  '本年停机率': 'Tỷ lệ dừng máy năm nay', '本月停机率': 'Tỷ lệ dừng máy tháng này',
  '本周停机率': 'Tỷ lệ dừng máy tuần này', '平均停机率': 'Tỷ lệ dừng máy trung bình',
  '各线停机率': 'Tỷ lệ dừng máy theo chuyền', '各线停机时间': 'Thời gian dừng theo chuyền',
  '各线停线时间': 'Thời gian dừng chuyền', '各线停线次数': 'Số lần dừng chuyền',
  '各种机台停机时间': 'Thời gian dừng theo loại máy',
  '近五日停机时间分布': 'Thời gian dừng 5 ngày gần đây',
  '年统计': 'Thống kê năm', '月趋势': 'Xu hướng tháng', '周趋势': 'Xu hướng tuần',
  '周趋势 (近7天)': 'Xu hướng tuần (7 ngày gần đây)',
  '月趋势 (近30天)': 'Xu hướng tháng (30 ngày gần đây)',
  '年统计 (近12月)': 'Thống kê năm (12 tháng gần đây)',
  '初始化停机率图表': 'Khởi tạo biểu đồ tỷ lệ dừng máy', '近': 'Gần đây',
  '設備統計表': 'Bảng thống kê thiết bị', '載板清潔': 'Vệ sinh bảng tải',
  '治具載板清潔': 'Vệ sinh bảng tải jig', '點檢項': 'Mục kiểm tra',

  /* ===== 数据库管理页 ===== */
  '数据库文件': 'Tệp cơ sở dữ liệu', '导出数据库文件': 'Xuất tệp CSDL',
  '导入数据库': 'Nhập cơ sở dữ liệu', '替换整个数据库': 'Thay thế toàn bộ CSDL',
  '选择文件': 'Chọn tệp', '开始导入': 'Bắt đầu nhập', '确认口令': 'Mã xác nhận',
  '整个数据库文件替换（原数据全部丢弃': 'Thay thế toàn bộ tệp CSDL (mất hết dữ liệu cũ',
  '脚本导入（脚本里已有的表会被覆盖，其它表保留': 'Nhập script (bảng có trong script sẽ bị ghi đè, bảng khác giữ nguyên',
  '勾选要清空的表（会同时重置自增序号，操作不可撤销':
    'Chọn bảng cần xóa (sẽ đặt lại số tự tăng, không thể hoàn tác',
  '此页面可直接读写数据库，请谨慎操作': 'Trang này đọc/ghi trực tiếp CSDL, hãy cẩn thận',
  '该物品暂未填写说明': 'Vật tư này chưa có mô tả',
  '点击查看说明': 'Bấm để xem mô tả',
  '说明加载失败，请重试': 'Tải mô tả thất bại, vui lòng thử lại',
  '清空、导入、执行 SQL 均需在弹窗中输入 CONFIRM 二次确认；操作前建议先导出数据库文件做备份。':
    'Muốn xóa, nhập hoặc thực thi SQL bạn phải nhập CONFIRM trong hộp thoại; nên xuất sao lưu trước.',
  '二次确认，操作前建议先「导出数据库文件」做备份': 'xác nhận hai lần, nên xuất sao lưu trước',
  '均需在弹窗中输入': 'đều phải nhập trong hộp thoại', '全部表': 'Tất cả bảng',
  '导出时间': 'Thời gian xuất', '导出本表': 'Xuất bảng này', '表数据': 'Dữ liệu bảng',
  '执行器': 'Trình thực thi', '执行确认': 'Xác nhận thực hiện', '确定清空': 'Xác nhận xóa',
  '确定删除': 'Xác nhận xóa', '删除确认': 'Xác nhận xóa',
  '确定执行下面的': 'Bạn có chắc muốn thực hiện',
  '语句会返回结果；其它语句': 'câu lệnh trả về kết quả; câu lệnh khác',
  '会直接执行': 'sẽ được thực hiện trực tiếp', '以确认执行': 'để xác nhận thực hiện',
  '以确认导入操作': 'để xác nhận nhập', '以确认清空操作': 'để xác nhận xóa',
  '关键字（全部字段模糊匹配': 'Từ khóa (tìm mờ tất cả trường',
  '点击行尾的「编辑': 'Nhấn "Sửa', '删除」操作': 'Xóa" ở cuối dòng',
  '(点击行尾的编辑 / 删除按钮操作)': '(nhấn Sửa / Xóa ở cuối dòng)',
  '行（最多显示': 'dòng (hiển thị tối đa', '已保存（影响': 'Đã lưu (ảnh hưởng',
  '已删除（影响': 'Đã xóa (ảnh hưởng',

  /* ===== 提示与错误 ===== */
  '失败': 'thất bại', '启动失败': 'Khởi động thất bại', '导入失败': 'Nhập thất bại',
  '加载失败': 'Tải thất bại', '数据获取失败': 'Lấy dữ liệu thất bại',
  '网络响应异常': 'Lỗi phản hồi mạng', '服务返回异常': 'Máy chủ trả về lỗi',
  '请求失败': 'Yêu cầu thất bại', '文件内容': 'nội dung tệp',
  '文件中没有任何数据表': 'Tệp không có bảng dữ liệu nào',
  '没有收到文件内容': 'Không nhận được nội dung tệp', '无法识别的': 'Không nhận dạng được',
  '没有可写入的字段': 'Không có trường để ghi',
  '没有需要更新的字段': 'Không có trường cần cập nhật', '没有数据': 'Không có dữ liệu',
  '缺少': 'Thiếu', '缺少主键列': 'thiếu cột khóa chính',
  '无法自动补齐': 'không thể tự bổ sung', '补列': 'thêm cột',
  '已自动补列': 'đã tự thêm cột', '数据库尚未初始化': 'CSDL chưa được khởi tạo',
  '表不存在': 'Không có bảng', '列不存在': 'Không có cột', '未知操作': 'Thao tác không xác định',
  '不支持的导出格式': 'Định dạng xuất không hỗ trợ',
  '请先选择文件': 'Vui lòng chọn tệp trước',
  '请先选择一张表': 'Vui lòng chọn một bảng trước',
  '请至少选择一张表': 'Vui lòng chọn ít nhất một bảng',
  '数据库中已存在数据': 'CSDL đã có dữ liệu', '跳过': 'Bỏ qua', '的导入': ' nhập',
  '若要用': 'Nếu muốn dùng', '重建，请删除': 'để tạo lại, hãy xóa',
  '已导入': 'Đã nhập', '已清空': 'Đã xóa', '已用': 'Đã dùng',
  '暂无数据，请调整查询条件后重试': 'Không có dữ liệu, vui lòng đổi điều kiện tìm kiếm',
  '没有数据，请调整查询条件后重试': 'Không có dữ liệu, vui lòng đổi điều kiện tìm kiếm',
  '的记录': ' bản ghi', '时间区间选择错误': 'Khoảng thời gian không hợp lệ',
  '时间格式错误': 'Sai định dạng thời gian', '日期選擇錯誤': 'Chọn ngày sai',
  '日期输入不正确': 'Nhập ngày không đúng', '时间必须是数字': 'Thời gian phải là số',
  '时间必须必须是数字': 'Thời gian phải là số', '数量必须是数字': 'Số lượng phải là số',
  '数量必须必须是数字': 'Số lượng phải là số', '數量必须是数字': 'Số lượng phải là số',
  '數量必须是数字，單位盒': 'Số lượng phải là số, đơn vị hộp',
  '积压必须是数字': 'Tồn đọng phải là số', '未选择日期范围': 'Chưa chọn khoảng ngày',
  '未检测到可用的局域网网卡地址': 'Không tìm thấy địa chỉ LAN khả dụng',
  '本机访问': 'Truy cập máy này',
  '局域网访问（其它电脑用下面的地址打开': 'Truy cập LAN (mở địa chỉ dưới đây trên máy khác',
  '端口': 'Cổng', '已被占用，本次改用': 'đã bị chiếm, lần này dùng',
  '及其备选端口均被占用。请关闭占用': 'và các cổng dự phòng đều bị chiếm. Hãy đóng chương trình đang dùng',
  '端口的程序': 'chương trình cổng', '另一个': 'khác', '连同': 'cùng với',
  '实例）后重试': 'instance) rồi thử lại', '后重新启动': ' rồi khởi động lại',
  '请释放该端口后重启本程序': 'hãy giải phóng cổng rồi khởi động lại chương trình',
  '如需恢复': 'Để khôi phục', '首次运行：正在导入': 'Chạy lần đầu: đang nhập',
  '未配置远程密码（环境变量': 'Chưa cấu hình mật khẩu từ xa (biến môi trường',

  /* ===== 知识点检（测验相关） ===== */
  '環境溫濕度不達標': 'Nhiệt độ/độ ẩm không đạt',
  '日常點檢不到位': 'Kiểm tra hàng ngày không đạt',
  '設備未按時保養': 'Thiết bị không bảo dưỡng đúng hạn',
  '未按流程作業': 'Không làm theo quy trình',
  '無用資料沒有及時清理': 'Dữ liệu vô ích không được dọn kịp thời',
  '無系統': 'Không', '开始答题': 'Bắt đầu làm bài', '開始答題': 'Bắt đầu làm bài',
  '正確選項': 'Đáp án đúng', '优秀！全部正确': 'Xuất sắc! Đúng hết',
  '不错，继续努力': 'Tốt, cố gắng tiếp', '需要加强练习哦': 'Cần luyện tập thêm',
  '非必填': 'Không bắt buộc',
};
